version: '2'

services:
  musicstore:
    build:
      context: ../../../
      dockerfile: src/MusicStore/Docker/Dockerfile.debug
      args:
        - CLRDBG_VERSION=${CLRDBG_VERSION}
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
